name = "shortener-service"
main = "worker/index.js"
compatibility_date = "2024-12-01"

[build]
command = "npm run build"

[env.production]
# Use Cloudflare Secrets instead of hardcoded values
# Add secrets using: wrangler secret put ADMIN_USER
# Add secrets using: wrangler secret put ADMIN_PASS
# Add secrets using: wrangler secret put SALT

[[d1_databases]]
binding = "DB"
database_name = "shortener-db"
database_id = "" 

[[kv_namespaces]]
binding = "KV"
id = "" 
