name = "shortener-service"
main = "worker/index.js"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
upload_dir = "public"

[env.production]
vars = { 
  ADMIN_USER = "your_admin@email.com",
  ADMIN_PASS = "YourSecurePassword123!",
  SALT = "随机生成盐值" # 用 openssl rand -hex 16 生成
}

[[d1_databases]]
binding = "DB"
database_name = "shortener-db"
database_id = "YOUR_DB_ID"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_ID"
